name: Build PDF

on:
  push:
    paths:
      - ".github/workflows/latex-build.yml"
      - "**.tex"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build PDF

    container:
      image: danteev/texlive:latest

    steps:
      - name: Download repo
        uses: actions/checkout@v2

      - name: Build PDF
        run: make doc

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v3
        with:
          name: My_Many_Reads
          path: proyecto.pdf
