name: Run spellchecker for latex and markdown files
on: 
  push:
    paths:
      - '**.md'
      - '**.tex'

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    name: Spellchecker

    steps:
    - name: Download repo
      uses: actions/checkout@v2

    - name: Install spellchecker tool
      run: sudo apt install aspell aspell-es aspell-en

    - name: Execute spellchecker target
      run: make spellcheck